Improve the ensure value interaction:
Make sure the error is on a new line so its readable
Use inplace assertions rather than files for simple results i.e. maven reactor tests
Add a new fail function as usage gives extra non sensical output in the scope of the ensure functions

diff --git a/branchout-environment b/branchout-environment
--- a/branchout-environment
+++ b/branchout-environment
@@ -3,10 +3,16 @@
 test -n "${DEBUG}" && set -x
 set -e
 
+function fail() {
+  test -n "${1}" && echo "${1}" && echo
+  exit 2
+}
+
 function readValue() {
   printf "Please provide %s: " "${1}"
   read -r VALUE
-  test -z "${VALUE}" && usage "Error: You must supply a value for $1"
+  echo
+  test -z "${VALUE}" && fail "Error: You must supply a value for $1"
   export "${2}=${VALUE}"
 }
 
@@ -14,7 +20,7 @@ function readSecret() {
   printf "Please provide %s: " "${1}"
   read -s -r VALUE
   echo
-  test -z "${VALUE}" && usage "Error: You must supply a value for $1"
+  test -z "${VALUE}" && fail "Error: You must supply a value for $1"
   export "${2}=${VALUE}"
 }
 
