branchout as one file for ease of installation

diff --git a/branchout b/branchout
--- a/branchout
+++ b/branchout
@@ -1,5 +1,196 @@
 #!/bin/bash
 
+
+function usage_branchout_project() {
+  echo "branchout project list|status|pull [project]
+  
+  status project-name
+      
+      Return the status of the given project, Not cloned, branch, rebasing
+  
+  pull project-name
+  
+      Attempt to pull the project, show the branch or error
+  
+  list [prefix]
+  
+      List all the projects with the given prefix
+  
+  "
+  
+  exit 1
+}
+
+function projectList() {
+  if test $# -eq 0; then
+    sort "${BRANCHOUT_DIRECTORY}/Branchoutprojects"
+  else
+    grep -e "^${1}" -e "^${BRANCHOUT_PREFIX}-${1}" "${BRANCHOUT_DIRECTORY}/Branchoutprojects" | sort
+  fi
+}
+
+function projectListWithGroups() {
+  sort <(cat "${BRANCHOUT_DIRECTORY}/Branchoutprojects") <(branchout_project groups)
+}
+
+
+function projectStatus() {
+   projectName=$(branchout_group deriveProject "${1}")
+   projectGroup=$(branchout_group derive "${1}")
+   if test -d "${BRANCHOUT_DIRECTORY}/${projectGroup}/${projectName}"; then
+     cd "${BRANCHOUT_DIRECTORY}/${projectGroup}/${projectName}" || usage_branchout_project "Failed to enter project directory"
+     
+     projectBranch=$(git rev-parse --abbrev-ref HEAD)
+     if test "${projectBranch}" = "master"; then
+       echo -e "\033[0m${2}${projectGroup}/${projectName}\033[70D\033[70C${projectBranch}\033[0m"
+     elif test "${projectBranch}" = "HEAD"; then
+       echo -e "\033[0m${2}${projectGroup}/${projectName}\033[70D\033[70C\033[38;5;202m<rebase>\033[0m"
+     else
+       echo -e "\033[0m${2}${projectGroup}/${projectName}\033[70D\033[70C\033[32m${projectBranch}\033[0m"
+     fi
+   else
+     echo -e "\033[0m${2}${projectGroup}/${projectName}\033[70D\033[70C\033[35mNot cloned\033[0m"
+   fi
+}
+
+function projectUpdateError() {
+  projectBranch=$(git rev-parse --abbrev-ref HEAD)
+  if test "${projectBranch}" = "HEAD"; then
+    echo -e "\033[0m${2}${projectGroup}/${1}\033[70D\033[70C\033[38;5;202m<rebase>\033[0m"
+  else
+    echo -e "\033[0m${2}\033[31m${projectGroup}/${1}\033[0m \033[70D\033[70C\033[1m $( git pull --rebase origin 2>&1| head -n1)\033[0m" 
+  fi
+}
+
+function projectUpdate() {
+  cd "${BRANCHOUT_DIRECTORY}/${projectGroup}/${projectName}" || usage_branchout_project "Failed to enter project directory"
+  git pull --rebase origin > /dev/null 2>&1 || projectUpdateError "${projectName}" "Failed "
+}
+
+function projectClone() {
+  test -d "${projectGroup}" || branchout_group pull "${projectGroup}"
+  cd "${projectGroup}" || useage_branchout_project "Project group ${projectGroup} directory not found"
+  echo -e "\033[0mCloning \033[92m${projectGroup}/${projectName}\033[0m"
+  RESULT=$(git clone "${BRANCHOUT_GIT_BASEURL}/${gitProject}" 2>&1)
+  if test $? -eq 0; then
+    projectStatus "${projectName}" "Pulled "
+  else
+    echo -e "\033[0mCloning failed: \033[31m${projectGroup}/${projectName}\n${RESULT}\033[0m"
+  fi
+}
+
+function projectPull() {
+   projectName=$(branchout_group deriveProject "${1}")
+   projectGroup=$(branchout_group derive "${1}")
+   gitProject="${1}"
+   if test -d "${BRANCHOUT_DIRECTORY}/${projectGroup}/${projectName}/.git"; then
+     projectUpdate 
+   else
+     projectClone 
+   fi
+}
+
+function branchout_project() {
+  case "${1}" in
+    list)
+      if test "${2}" = "--grouped"; then
+        projectListWithGroups
+      else
+        projectList "${2}"
+      fi
+      ;;
+    status)
+      test -n "${2}" || usage_branchout_project "Must provide project"
+      projectStatus "${2}"
+      ;;
+    pull)
+      test -n "${2}" || usage_branchout_project "Must provide project"
+      projectPull "${2}"
+      ;;
+    *)
+      usage_branchout_project
+  esac
+}
+
+function usage_branchout_group() {
+  echo "branchout group derive [project]
+  
+  status 
+      
+      Return the status of the given group, Not cloned, branch, rebasing
+  
+  pull group
+  
+      Attempt to pull the group, show the branch or error
+  
+  list
+  
+      List all the groups
+      
+  STDIN
+  
+      Derive the group for all the projects piped in
+  
+  "
+  
+  exit 1
+}
+
+function branchoutGroupDeriveStdin() {
+  # STDIN is always derived
+  while read -r each; do
+    branchoutGroupDerive "${each}"
+  done
+}
+
+function branchoutGroupClone() {
+  test -d "${1}"|| mkdir "${1}"
+}
+
+function branchoutGroups() {
+  branchout_project list "${1}" | branchout_group derive --stdin | sort | uniq
+}
+
+function branchoutGroupDerive() {
+  if test -z "${BRANCHOUT_PREFIX}"; then
+    echo "${1%%-*}"
+  else
+    noPrefix="${1#${BRANCHOUT_PREFIX}-}"
+    echo "${noPrefix%%-*}"
+  fi
+
+}
+
+function branchoutProjectDerive() {
+  echo "${1}"
+}
+
+function branchout_group() {
+  case $1 in
+    derive) 
+      if test "${2}" = "--stdin"; then
+        branchoutGroupDeriveStdin
+      else
+        branchoutGroupDerive "${2}"
+      fi
+      ;;
+    deriveProject) 
+      branchoutProjectDerive "${2}"
+      ;;
+    pull)
+      test -n "${2}" || usage_branchout_group "Must provide group"
+      branchoutGroupClone "${2}"
+      ;;
+    list)
+      branchoutGroups "${2}"
+      ;;
+
+    *)
+      usage_branchout_project
+      ;;
+  esac
+}
+
 function usage() {
   test -n "${1}" && echo "${1}" && echo
   echo "branchout: a tool for managing multi-repo projects
@@ -19,6 +210,7 @@ function branchoutDirectory() {
 }
 
 function loadBranchout() {
+  test -n "${BRANCHOUT_LOADED}" && return 0
   branchoutDirectory
   
   # shellcheck source=examples/Branchoutfile
@@ -33,6 +225,8 @@ function loadBranchout() {
   
   test ! -d "${BRANCHOUT_HOME}" && usage "Branchout home '${BRANCHOUT_HOME}' does not exist, run branchout init"
   test -f "${BRANCHOUT_DIRECTORY}/Branchoutprojects" || usage "Branchoutprojects file missing, try branchout add [repository]"
+  
+  export BRANCHOUT_LOADED="true"
 }
 
 function branchoutProjects() {
@@ -48,16 +242,24 @@ function branchoutProjectStatus() {
   fi
 }
 
+function branchout_status() {
+  branchout_project list "${1}" | xargs -P"${BRANCHOUT_THREADS-10}" -I{} branchout project status {}
+}
+
+function branchout_pull() {
+  branchout_project list "${1}" | xargs -P"${BRANCHOUT_THREADS-10}" -I{} branchout project pull {}
+}
+
 
 function main() {
   test $# -gt 0 || usage
   loadBranchout
   branchoutModule="${1}"
   shift
-  if which branchout-"${branchoutModule}" >/dev/null; then
-    exec branchout-"${branchoutModule}" "${@}"
+  if declare -f -F branchout_"${branchoutModule}" >/dev/null; then
+    eval branchout_"${branchoutModule}" "${@}"
   else
-    exec branchout-pull "${branchoutModule}" "${@}"
+    eval branchout_pull "${branchoutModule}" "${@}"
   fi
 }
 
