Correctly fail when the .branchout file is not found

diff --git a/branchout b/branchout
--- a/branchout
+++ b/branchout
@@ -2,10 +2,26 @@
 
 function branchoutDirectory() {
   BRANCHOUT_DIRECTORY="${PWD}"
-  while test ! -f "${PROJECT_DIRECTORY}/.branchout"; do
-    PROJECT_DIRECTORY=$(dirname "${PROJECT_DIRECTORY}")
-    test "${PROJECT_DIRECTORY}" = '/' && echo ".branchout not found in parent directories" && exit 127
+  while test ! -f "${BRANCHOUT_DIRECTORY}/.branchout"; do
+    BRANCHOUT_DIRECTORY=$(dirname "${BRANCHOUT_DIRECTORY}")
+    test "${BRANCHOUT_DIRECTORY}" = '/' && echo ".branchout configuration not found in parent hierarchy, run branchout init" && exit 1
   done
+  export BRANCHOUT_DIRECTORY
 }
 
-echo "branchout: a tool for managing multi-repo projects"
+function branchoutStatus() {
+  branchoutDirectory
+}
+
+
+case "$1" in
+  status)
+    branchoutStatus
+    ;;
+  *)
+    echo "branchout: a tool for managing multi-repo projects
+    
+    status: show the list of known projects and their current state
+    "
+    ;;
+esac
