Clean up values and configs:
Move all the value and config functions into branchout-configuration to make it easier to import them and reuse them, branchout-environment is overloaded with meaning

Make sure that all values in the Branchoutfile are prefixed with BRANCHOUT_ just like the configs.

Only source the branchout-configuration when its used, make debugging a lot easier

Add suport for default values in readValue and ensure functions, this means you can say things like

```
ensureValue "user" USER "${USER}"
```
this will prompt for user but if not provided fall back to an existing or derived value

Use the value functions direct to avoid an external call

Make sure to use consistent naming across the value and config functions so its easy to get the code right

diff --git a/branchout-configuration b/branchout-configuration
--- a/branchout-configuration
+++ b/branchout-configuration
@@ -3,6 +3,78 @@
 test -n "${DEBUG}" && set -x
 set -e
 
+function fail() {
+  test -n "${1}" && echo "${1}" && echo
+  exit 2
+}
+
+function getConfigValue() {
+  test -z "${BRANCHOUT_STATE}" && fail "BRANCHOUT_STATE is not defined"
+  if test -f "${BRANCHOUT_STATE}/branchoutrc"; then
+    grep "^BRANCHOUT_CONFIG_${1}=" "${BRANCHOUT_STATE}/branchoutrc" | sed -e 's,^.*="\(.*\)"$,\1,'
+  fi
+}
+
+function setConfigValue() {
+  test -z "${BRANCHOUT_STATE}" && fail "BRANCHOUT_STATE is not defined"
+  test -z "${2}" && usage "You must supply a value to set"
+  test -f "${BRANCHOUT_STATE}/branchoutrc" && grep -v "^BRANCHOUT_CONFIG_${1}=" "${BRANCHOUT_STATE}/branchoutrc" > "${BRANCHOUT_STATE}/branchoutrc.tmp" && true
+  echo "BRANCHOUT_CONFIG_${1}=\"${2}\"" >> "${BRANCHOUT_STATE}/branchoutrc.tmp"
+  sort "${BRANCHOUT_STATE}/branchoutrc.tmp" > "${BRANCHOUT_STATE}/branchoutrc"
+  rm "${BRANCHOUT_STATE}/branchoutrc.tmp"
+}
+
+function getValue() {
+  test -z "${BRANCHOUT_STATE}" && fail "BRANCHOUT_STATE is not defined"
+  grep "^BRANCHOUT_${1}=" "${PROJECTION_DIRECTORY}/${BRANCHOUT_FILE}" | sed -e 's,^.*="\(.*\)"$,\1,'
+}
+
+function setValue() {
+  test -z "${PROJECTION_DIRECTORY}" && fail "PROJECTION_DIRECTORY is not defined"
+  grep -v "^BRANCHOUT_${1}=" "${PROJECTION_DIRECTORY}/${BRANCHOUT_FILE}" > "${PROJECTION_DIRECTORY}/${BRANCHOUT_FILE}".tmp && true
+  echo "BRANCHOUT_${1}=\"${2}\"" >> "${PROJECTION_DIRECTORY}/${BRANCHOUT_FILE}.tmp"
+  sort "${PROJECTION_DIRECTORY}/${BRANCHOUT_FILE}.tmp" > "${PROJECTION_DIRECTORY}/${BRANCHOUT_FILE}"
+  rm "${PROJECTION_DIRECTORY}/${BRANCHOUT_FILE}.tmp"
+}
+
+function readValue() {
+  if test -z "${3}"; then
+    printf "Please provide %s: " "${1}"
+  else
+    printf "Please provide %s [%s]: " "${1}" "${3}"
+  fi
+  # if the user does not enter a value sure to add a newline before the error message if there is no default
+  read -r VALUE || true
+  echo
+  test -z "${VALUE}" && VALUE="${3}"
+  test -z "${VALUE}" && fail "Error: You must supply a value for $1"
+  export "${2}=${VALUE}"
+}
+
+function readSecret() {
+  printf "Please provide %s: " "${1}"
+  read -s -r VALUE
+  echo
+  test -z "${VALUE}" && fail "Error: You must supply a value for $1"
+  export "${2}=${VALUE}"
+}
+
+function ensureValue() {
+  valueName="BRANCHOUT_${2}"
+  if test -z "${!valueName}"; then
+    readValue "${1}" "${valueName}" "${3}"
+    setValue "${2}" "${!valueName}"
+  fi
+}
+
+function ensureConfigValue() {
+  configName="BRANCHOUT_CONFIG_${2}"
+  if test -z "${!configName}"; then
+    readValue "${1}" "${configName}" "${3}"
+    setConfigValue "${2}" "${!configName}"
+  fi
+}
+
 export BO_THEME_RESET="\\033[0m"
 export BO_THEME_OK="\\033[0m"
 export BO_THEME_NOTICE="\\033[35m"
