rename one,two,three to better ordered names
* First pull test works

diff --git a/branchout-project b/branchout-project
--- a/branchout-project
+++ b/branchout-project
@@ -37,26 +37,30 @@ function projectStatus() {
    if test -d "${BRANCHOUT_DIRECTORY}/${projectGroup}/${1}"; then
      cd "${BRANCHOUT_DIRECTORY}/${projectGroup}/${1}" || usage "Failed to enter project directory"
      projectBranch=$(git rev-parse --abbrev-ref HEAD)
-     echo -e "${projectGroup}/${1}\033[70D\033[70C\033[32m${projectBranch}\033[0m"
+     if test "${projectBranch}" = "master"; then
+       echo -e "\033[0m${2}${projectGroup}/${1}\033[70D\033[70C\033m${projectBranch}\033[0m"
+     else
+       echo -e "\033[0m${2}${projectGroup}/${1}\033[70D\033[70C\033[32m${projectBranch}\033[0m"
+     fi
    else
-     echo -e "${projectGroup}/${1}\033[70D\033[70C\033[35mNot cloned\033[0m"
+     echo -e "\033[0m${2}${projectGroup}/${1}\033[70D\033[70C\033[35mNot cloned\033[0m"
    fi
 }
 
 function projectUpdate() {
   cd "${BRANCHOUT_DIRECTORY}/${projectGroup}/${1}" || usage "Failed to enter project directory"
-  git pull --rebase origin > /dev/null 2>&1 || (echo -e "Failed: \033[31m${projectGroup}/${1}\033[0m \033[70D\033[70C\033[1m $( git pull --rebase origin 2>&1| head -n1)\033[0m")
+  git pull --rebase origin > /dev/null 2>&1 || (echo -e "\033[0mFailed: \033[31m${projectGroup}/${1}\033[0m \033[70D\033[70C\033[1m $( git pull --rebase origin 2>&1| head -n1)\033[0m")
 }
 
 function projectClone() {
   test -d "${projectGroup}" || branchout-group pull "${projectGroup}"
   cd "${projectGroup}" || useage "Project group ${projectGroup} directory not found"
-  echo -e "Cloning Project: \033[92m${projectGroup}/${1}\033[0m"
-  RESULT=$(git clone "${BRANCHOUT_GIT_BASEURL}/${1}.git")
+  echo -e "\033[0mCloning \033[92m${projectGroup}/${1}\033[0m"
+  RESULT=$(git clone "${BRANCHOUT_GIT_BASEURL}/${1}" 2>&1)
   if test $? -eq 0; then
-    projectStatus "${1}"
+    projectStatus "${1}" "Pulled "
   else
-    echo -e "Cloning failed: \033[31m${projectGroup}/${1}\n${RESULT}\033[0m"
+    echo -e "\033[0mCloning failed: \033[31m${projectGroup}/${1}\n${RESULT}\033[0m"
   fi
 }
 
